### ISSUE TITLE
Would it be possible to prevent building in protected areas?

### ISSUE THREAD

**Issue by CosmicVoyager** [jrbudda/Builder#22]
Greetings,

Would it be possible to prevent building in protected areas? Precious stones and WorldGuard areas?

Thanks

**Comment by wolfbane8653** [comment]
In the config.yml you should see the DefaultOptions.

DefaultOptions:
  MoveTimeoutSeconds: 2.0
  IgnoreProtection: false #not working
  HoldItems: true
  RequireMaterials: false

I would assume that the given option marked with the comment #notworking would mean yes but they are still working on it. However, until stated otherwise that doesn't seem like it really isn't working right now. Try setting it to true and see what happens. Then post your log files if any errors occur. I would assume there will need to be a bridge plugin for each protection plugin.

**Comment by jrbudda** [comment]
No, it's not really possible. Most protection plugins need a valid online player to check against, and I've not found a way around that.
