### ISSUE TITLE
Builder will not accept certain items

### ISSUE THREAD

**Issue by CosmicVoyager** [jrbudda/Builder#23]
Greetings,

When ou try to give the builder some things he says he needs, he says he does not need i.

An example is jungle wood stairs. I will add more items as encountered.

Thanks

**Comment by jrbudda** [comment]
I'm guessing you're using the new RequireUnobtainable setting. I think I see the issue there. Will fix.

**Comment by jrbudda** [comment]
Try this http://www.sendspace.com/file/gbijup

**Comment by CosmicVoyager** [comment]
Hello, another such problem. Bob will not accept an iron door. In the build the iron door has a value of 71:8, but the iron door you make is 71.

Would it be possible to set which items are unobtainable in the config? And list items that are not required, such as fire?

**Comment by jrbudda** [comment]
Actually the door in your hand is 330. I will look and see about maybe allowing full customization.

**Comment by jrbudda** [comment]
k try this http://www.sendspace.com/file/1par8y

Ive removed the 'require unobtainable" option in lieu of a supply.txt file that specifies exactly what block id requires what (and optinally how much). The default file (which will be created on first load) is set up like standard Builder. Anything not specified in the txt file will default to it's normal drop item. So in your case you'd want to specify most blocks require themselves.

Example: for Cobwebs to require cobwebs instead of string, add "30:30" to the file and call /builder reload.
